### ISSUE TITLE
cannot unmarshal object into Go value of type float64

### ISSUE THREAD

**Issue by busecolak** [PBWebMedia/yarn-prometheus-exporter#2]
Hello, 

I'm trying to integrate the yarn-prometheus-exporter using Docker, but I am getting an error regarding unmarshaling json value. 

Running the exporter using following command:
`docker run -it -d --name yarn-exporter -p 9113:9113 -e "YARN_PROMETHEUS_ENDPOINT_HOST=172.17.0.1" pbweb/yarn-prometheus-exporter`

Resource Manager version is 3.2.1. 

The error message is:
`Error while collecting data from YARN: json: cannot unmarshal object into Go value of type float64`

How can I resolve this?

**Comment by maxrem** [comment]
This is fixed
