### ISSUE TITLE
Need ability to ignore hostname validation in http request (similar to -k in curl)

### ISSUE THREAD

**Issue by zbialik** [PBWebMedia/yarn-prometheus-exporter#3]
When I test out the curl of the metrics, it should result in additional metrics returned from the yarn-resource-manager.

However, logs show that it cant connect due to hostname validation. Is there a way this can be customized at deploy time?

**Comment by RPCMoritz** [comment]
I just mounted my trust store into the container:
``` -v /etc/ssl/ca-bundle.pem:/etc/ssl/ca-bundle.pem```
That picked up the certificate chain, and now everything works.

**Comment by zbialik** [comment]
Yep ended up doing the same, thanks @RPCMoritz
